version: "3.9"

services:
  # Main service to run the full pipeline
  pipeline:
    build: .
    container_name: breweries_pipeline
    volumes:
      - ./data:/app/data
    working_dir: /app
    command: bash -c "\
      python src/api/breweries_api.py && \
      python src/transformations/bronze_to_silver.py && \
      python src/transformations/silver_to_gold.py"
    tty: true

  # Service for the Bronze layer only (extraction)
  bronze:
    build: .
    container_name: breweries_bronze
    volumes:
      - ./data:/app/data
    working_dir: /app
    command: python src/api/breweries_api.py
    tty: true

  # Service for the Silver layer only (transformation)
  silver:
    build: .
    container_name: breweries_silver
    volumes:
      - ./data:/app/data
    working_dir: /app
    command: python src/transformations/bronze_to_silver.py
    tty: true

  # Service for the Gold layer only (aggregation)
  gold:
    build: .
    container_name: breweries_gold
    volumes:
      - ./data:/app/data
    working_dir: /app
    command: python src/transformations/silver_to_gold.py
    tty: true

  # Service to run tests
  tests:
    build: .
    container_name: breweries_tests
    volumes:
      - ./data:/app/data
    working_dir: /app
    command: pytest tests/
    tty: true
